---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: postgresql
      property: admin_password
