---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: semaphore-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: semaphore
      property: postgres_password
  - secretKey: SEMAPHORE_DB_PASS
    remoteRef:
      key: semaphore
      property: postgres_password
  - secretKey: SEMAPHORE_ADMIN
    remoteRef:
      key: semaphore
      property: admin_username
  - secretKey: SEMAPHORE_ADMIN_NAME
    remoteRef:
      key: semaphore
      property: admin_name
  - secretKey: SEMAPHORE_ADMIN_PASSWORD
    remoteRef:
      key: semaphore
      property: admin_password
  - secretKey: SEMAPHORE_ADMIN_EMAIL
    remoteRef:
      key: semaphore
      property: admin_email
  - secretKey: SEMAPHORE_ACCESS_KEY_ENCRYPTION
    remoteRef:
      key: semaphore
      property: access_key_encryption
